version: "3.8"

services:
  web:
   build:
    dockerfile: ./dockerfile
   ports:
    - "4000:4000"
   depends_on:
    - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword